export const company = {
  name: 'BLM Motors',
  legalName: 'BLM Motors',
  tagline: "It's not just a ride, it's an adventure.",
  homeBase: 'Nigeria',
  summary:
    'Reliable 24/7 transport, car hire, touring, pickup, interstate movement, and cross-border trips from Nigeria to Benin Republic, Togo, and Ghana.',
  email: 'bookings@blmmotors.ng',
  phone: '+2349064090276',
  phoneDisplay: '+234 906 409 0276',
  beninPhone: '+2290142439626',
  beninPhoneDisplay: '+229 01 42 43 96 26',
  whatsapp: '+2290142439626',
  whatsappDisplay: 'WhatsApp',
  whatsappMessage: 'Good day BLM, I want to book your services',
  address: 'Nigeria operations desk',
  logo: '/brand/blm-logo.png',
  heroImage: '/brand/login-hero.png',
  servicesImage: '/brand/car-02.png',
  qualities: ['Fast', 'Secure', 'Reliable'],
  routes: [
    'Within Nigeria',
    'Benin Republic to Nigeria',
    'Nigeria to Benin Republic',
    'Ghana to Togo',
    'Togo to Benin Republic',
    'Interstate movement',
  ],
  services: [
    {
      icon: 'schedule',
      title: '24/7 transport services',
      desc: 'Round-the-clock private and business transport with booking records, payment tracking, and dispatch updates.',
    },
    {
      icon: 'route',
      title: 'Cross-border trips',
      desc: 'Nigeria, Benin Republic, Togo, and Ghana routes for planned passenger movement and logistics support.',
    },
    {
      icon: 'explore',
      title: 'Touring',
      desc: 'Tour plans, airport pickup, city movement, and guided multi-stop travel for visitors and groups.',
    },
    {
      icon: 'local_taxi',
      title: 'Car hire',
      desc: 'Short-term and scheduled car hire for errands, executive movement, events, and family travel.',
    },
    {
      icon: 'inventory_2',
      title: 'Pickup and logistics',
      desc: 'Document, parcel, retail, and business pickup with traceable booking and delivery status.',
    },
    {
      icon: 'moving',
      title: 'Long and short distance trips',
      desc: 'Flexible local, interstate, and regional trips with the right vehicle class for the route.',
    },
  ],
  hubs: [
    { name: 'Lagos', address: 'Lagos, Nigeria' },
    { name: 'Abuja', address: 'Abuja, Nigeria' },
    { name: 'Port Harcourt', address: 'Port Harcourt, Nigeria' },
    { name: 'Enugu', address: 'Enugu, Nigeria' },
    { name: 'Ibadan', address: 'Ibadan, Nigeria' },
    { name: 'Kano', address: 'Kano, Nigeria' },
    { name: 'Owerri', address: 'Owerri, Nigeria' },
    { name: 'Benin City', address: 'Benin City, Nigeria' },
    { name: 'Cotonou', address: 'Cotonou, Benin Republic' },
    { name: 'Lome', address: 'Lome, Togo' },
    { name: 'Accra', address: 'Accra, Ghana' },
  ],
  touringStates: [
    { name: 'Lagos', factor: 1 },
    { name: 'Abuja', factor: 1.15 },
    { name: 'Port Harcourt', factor: 1.18 },
    { name: 'Enugu', factor: 1.2 },
    { name: 'Ibadan', factor: 1.08 },
    { name: 'Kano', factor: 1.22 },
    { name: 'Owerri', factor: 1.16 },
    { name: 'Benin City', factor: 1.12 },
  ],
  internationalTours: [
    { name: 'Benin Republic', factor: 1.1 },
    { name: 'Ghana', factor: 1.2 },
    { name: 'Togo', factor: 1.08 },
  ],
  carHireOptions: [
    { id: 'toyota-corolla', name: 'Toyota Corolla', seats: 4, desc: 'Sedan for airport transfer, meetings, and city travel.', image: '/brand/car-01.png' },
    { id: 'toyota-highlander', name: 'Toyota Highlander', seats: 6, desc: 'Spacious crossover for family and executive movement.', image: '/brand/car-02.png' },
    { id: 'bus-mini', name: 'Mini Bus', seats: 14, desc: 'Group travel for events, tours, and shared pickups.', image: '/brand/car-03.png' },
  ],
};

export const defaultVehicles = [
  { title: 'Economy', desc: 'Affordable city rides and short-distance transport.', price: 25000, icon: 'directions_car' },
  { title: 'Business', desc: 'Premium executive transport for city and interstate travel.', price: 65000, icon: 'airport_shuttle' },
  { title: 'Cross-Border transit', desc: 'Nigeria, Benin Republic, Togo, and Ghana cross-border trips.', price: 180000, icon: 'route' },
  { title: 'Touring Bronze', desc: 'Entry-level touring with flexible stop counts for major states.', price: 90000, icon: 'tour' },
  { title: 'Touring Silver', desc: 'Comfort touring with extra spots and better local support.', price: 130000, icon: 'travel_explore' },
  { title: 'Touring Gold', desc: 'Executive touring package for business groups and extended schedules.', price: 180000, icon: 'emoji_events' },
  { title: 'Touring Platinum', desc: 'Luxury touring with premium service, stops, and support.', price: 250000, icon: 'stars' },
  { title: 'Pickup & Logistics', desc: 'Parcel, retail, and business pickup with traceable tracking.', price: 65000, icon: 'local_shipping' },
  { title: 'Car Hire', desc: 'Private hire with caution fee and damage consent protection.', price: 70000, icon: 'car_rental' },
  { title: 'International Tour', desc: 'Benin, Ghana, and Togo touring with pricing by stops.', price: 220000, icon: 'public' },
];
