export const company = {
  name: 'BLM Motors',
  legalName: 'BLM Motors',
  tagline: "It's not just a ride, it's an adventure.",
  homeBase: 'Nigeria',
  summary:
    'Reliable 24/7 transport, car hire, touring, pickup, interstate movement, and cross-border trips from Nigeria to Benin Republic, Togo, and Ghana.',
  email: 'bookings@blmmotors.ng',
  phone: '+2290142439626',
  phoneDisplay: '+229 01 42 43 96 26',
  beninPhone: '+2290142439626',
  beninPhoneDisplay: '+229 01 42 43 96 26',
  whatsapp: '+2349064090276',
  whatsappDisplay: 'WhatsApp',
  whatsappMessage: 'Good day BLM, I want to book your services',
  address: 'Nigeria operations desk',
  logo: '/brand/blm-logo-wide.png',
  heroImage: '/brand/hero-fleet-v2.webp',
  servicesImage: '/brand/services-corridor-v3.webp',
  transportHeroImage: '/brand/services-corridor-v3.webp',
  authImage: '/brand/login-pickup-v2.webp',
  weekendFlyerImage: '/brand/blm-logo-wide.png',
  qualities: ['Fast', 'Secure', 'Reliable'],
  routes: [
    'Within Nigeria',
    'Benin Republic to Nigeria',
    'Nigeria to Benin Republic',
    'Ghana to Togo',
    'Togo to Benin Republic',
    'Interstate movement',
  ],
  services: [
    {
      icon: 'moving',
      title: 'Long and short distance trips',
      desc: 'Round-the-clock local, interstate, and regional transport priced accurately per kilometer.',
      vehicleClass: 'Business',
    },
    {
      icon: 'route',
      title: 'Cross-border trips',
      desc: 'Nigeria, Benin Republic, Togo, and Ghana routes for planned passenger movement and logistics support.',
      vehicleClass: 'Cross-Border transit',
    },
    {
      icon: 'explore',
      title: 'Touring',
      desc: 'Curated touring packages, airport pickup, city movement, and guided travel across premium destinations.',
      vehicleClass: 'Touring Basic',
    },
    {
      icon: 'local_taxi',
      title: 'Car hire',
      desc: 'Short-term and scheduled car hire from designated pickup locations with or without professional chauffeur.',
      vehicleClass: 'Car Hire',
    },
    {
      icon: 'inventory_2',
      title: 'Pickup and logistics',
      desc: 'Direct doorstep parcel, retail, and cargo pickup with traceable tracking and weight-based pricing.',
      vehicleClass: 'Pickup & Logistics',
    },
  ],
  hubs: [
    { name: 'Lagos - Ikeja Terminal', address: 'Ikeja Central Terminal, Lagos, Nigeria' },
    { name: 'Lagos - Victoria Island Hub', address: 'VI Executive Depot, Lagos, Nigeria' },
    { name: 'Lagos - Lekki Phase 1', address: 'Admiralty Way Hub, Lekki, Lagos, Nigeria' },
    { name: 'Abuja - Central Hub', address: 'Central Business District, Abuja, Nigeria' },
    { name: 'Port Harcourt Hub', address: 'Aba Road Terminal, Port Harcourt, Nigeria' },
    { name: 'Ibadan Hub', address: 'Ring Road Operations Hub, Ibadan, Nigeria' },
    { name: 'Enugu Hub', address: 'Independence Layout, Enugu, Nigeria' },
    { name: 'Benin City Hub', address: 'Airport Road, Benin City, Nigeria' },
    { name: 'Cotonou Station', address: 'Haie Vive, Cotonou, Benin Republic' },
    { name: 'Lome Station', address: 'Boulevard du 13 Janvier, Lome, Togo' },
    { name: 'Accra Station', address: 'Airport City, Accra, Ghana' },
  ],
  touringPackages: [
    { id: 'touring-basic', title: 'Touring Basic', name: 'Basic City Explorer', desc: '2-location guided city route with essential cultural highlights.', price: 90000, locations: 2, days: 2 },
    { id: 'touring-classic', title: 'Touring Classic', name: 'Classic Cultural Journey', desc: '5-location heritage and city route with guided stop coverage.', price: 140000, locations: 5, days: 5 },
    { id: 'touring-premium', title: 'Touring Premium', name: 'Premium VIP Heritage', desc: '10-location premium route with priority access and chauffeur support.', price: 200000, locations: 10, days: 10 },
    { id: 'touring-luxury', title: 'Touring Luxury', name: 'Luxury Scenic Expedition', desc: 'Custom multi-location scenic experience with luxury support.', price: 280000, locations: 12, days: 12 },
    { id: 'touring-diamond', title: 'Touring Diamond', name: 'Diamond Royal Experience', desc: 'Bespoke premium route plan built for elevated long-form touring.', price: 400000, locations: 15, days: 15 },
  ],
  touringStates: [
    { name: 'Lagos', factor: 1 },
    { name: 'Ogun', factor: 1.04 },
    { name: 'Oyo', factor: 1.08 },
    { name: 'Osun', factor: 1.09 },
    { name: 'Ondo', factor: 1.11 },
    { name: 'Ekiti', factor: 1.12 },
    { name: 'Edo', factor: 1.13 },
    { name: 'Delta', factor: 1.15 },
    { name: 'Kwara', factor: 1.16 },
    { name: 'Kogi', factor: 1.18 },
    { name: 'FCT Abuja', factor: 1.2 },
    { name: 'Anambra', factor: 1.21 },
    { name: 'Enugu', factor: 1.22 },
    { name: 'Imo', factor: 1.23 },
    { name: 'Abia', factor: 1.24 },
    { name: 'Rivers', factor: 1.25 },
    { name: 'Bayelsa', factor: 1.26 },
    { name: 'Ebonyi', factor: 1.27 },
    { name: 'Cross River', factor: 1.3 },
    { name: 'Akwa Ibom', factor: 1.31 },
    { name: 'Benue', factor: 1.28 },
    { name: 'Nasarawa', factor: 1.24 },
    { name: 'Plateau', factor: 1.31 },
    { name: 'Niger', factor: 1.25 },
    { name: 'Kaduna', factor: 1.34 },
    { name: 'Kano', factor: 1.38 },
    { name: 'Katsina', factor: 1.42 },
    { name: 'Jigawa', factor: 1.43 },
    { name: 'Bauchi', factor: 1.4 },
    { name: 'Gombe', factor: 1.44 },
    { name: 'Taraba', factor: 1.46 },
    { name: 'Adamawa', factor: 1.5 },
    { name: 'Yobe', factor: 1.52 },
    { name: 'Borno', factor: 1.58 },
    { name: 'Sokoto', factor: 1.52 },
    { name: 'Kebbi', factor: 1.5 },
    { name: 'Zamfara', factor: 1.49 },
  ],
  internationalTours: [
    { name: 'Benin Republic', factor: 1.1 },
    { name: 'Ghana', factor: 1.2 },
    { name: 'Togo', factor: 1.08 },
  ],
  carHireOptions: [
    { id: 'toyota-corolla', name: 'Toyota Corolla', seats: 4, desc: 'Sedan for airport transfer, meetings, and city travel.', image: '/brand/car-01.webp' },
    { id: 'toyota-highlander', name: 'Toyota Highlander', seats: 6, desc: 'Spacious crossover for family and executive movement.', image: '/brand/car-02.webp' },
    { id: 'bus-mini', name: 'Mini Bus', seats: 14, desc: 'Group travel for events, tours, and shared pickups.', image: '/brand/car-03.webp' },
  ],
  pricingRules: {
    pricePerKm: 350,
    logisticsPricePerKm: 250,
    standardServiceFee: 4500,
    touringPerLocation: 15000,
    internationalTourPerLocation: 25000,
    pickupLogisticsFee: 22000,
    pricePerKg: 1200,
    carHireCautionFee: 25000,
    crossBorderProcessingFee: 30000,
    crossBorderBasePerPassenger: 90000,
    defaultRouteFactor: 1,
    returnMultiplier: 2,
    maxTouringLocations: 20,
  },
};

export const defaultVehicles = [
  { title: 'Economy', desc: 'Standard sedan for short and medium distance trips.', price: 25000, kmRate: 300, icon: 'directions_car' },
  { title: 'Business', desc: 'Premium executive vehicle for interstate and business distance travel.', price: 45000, kmRate: 450, icon: 'airport_shuttle' },
  { title: 'Executive SUV', desc: 'Luxury high-clearance SUV for ultimate comfort on regional routes.', price: 75000, kmRate: 700, icon: 'directions_car' },
  { title: 'Cross-Border transit', desc: 'Nigeria, Benin Republic, Togo, and Ghana cross-border trips.', price: 180000, icon: 'route' },
  { title: 'Touring Basic', desc: 'Basic City Explorer - 1-day essential city tour.', price: 90000, icon: 'tour' },
  { title: 'Touring Classic', desc: 'Classic Cultural Journey - 2-day heritage sites tour.', price: 140000, icon: 'travel_explore' },
  { title: 'Touring Premium', desc: 'Premium VIP Heritage - 3-day guided excursion.', price: 200000, icon: 'emoji_events' },
  { title: 'Touring Luxury', desc: 'Luxury Scenic Expedition - 5-day resort and nature tour.', price: 280000, icon: 'stars' },
  { title: 'Touring Diamond', desc: 'Diamond Royal Experience - 7-day all-inclusive VIP tour.', price: 400000, icon: 'diamond' },
  { title: 'Pickup & Logistics', desc: 'Parcel, retail, and business pickup with doorstep collection.', price: 65000, icon: 'local_shipping' },
  { title: 'Car Hire', desc: 'Private hire from designated pickup locations with refundable caution fee.', price: 70000, icon: 'car_rental' },
  { title: 'International Tour', desc: 'Benin, Ghana, and Togo touring expeditions.', price: 220000, icon: 'public' },
];
